name: Generate Graph

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Make sure to have a requirements.txt file

    - name: Generate graph
      run: |
        python ranking.py # Your script to generate the graph

    - name: Update changes in repo
      uses: EndBug/add-and-commit@v9
      with:
        add: -f result.png
        github_token: ${{secrets.TOKEN_GITHUB}}
