name: Generate Graph

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Make sure to have a requirements.txt file

    - name: Generate graph
      run: |
        python ranking.py # Your script to generate the graph

    - name: Commit and push the graph
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add -f graph.png
        git commit -m 'Update graph'
        git push

